# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcfac7e62e971e84d348afda63fcc98e61b14c9ab08961bd6bcb8a10bcc870cde41383556728f0e56ae1c2161519a5cfb1d3f7f68095ab1193bc4494f4f8a0bf

test:
  secret_key_base: 0643f1368f1109f6f4dd0b553274cdd8fb0ded8315021202104c3b8c03a8041f37e208c992f90c629bfd7b843b72139078e8580356c89a25d0fbc3b09a185363

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
